add_newline = false
"$schema" = 'https://starship.rs/config-schema.json'
[character]
success_symbol = "[â¯](bold bright-green)"
format = "$sudo$symbol$shell "
error_symbol = "[âœ—](red bold)"
vicmd_symbol="[â®](bold green)"
[python]
symbol="ğŸ"


